name: ci

on: [ push, pull_request ]

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    steps:
      - name: add sudo
        run: apt update && apt install sudo
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: install tfswitch
        run: curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sudo bash
      -
        name: get terraform
        run: sudo tfswitch
      -
        name: terraform init 
        run: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && echo "$m - init" && terraform init -input=false -backend=false) || exit 1; done
      -
        name: terraform validate
        run: find . -name ".terraform" -prune -o -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && echo "$m - validate" && terraform validate && echo "√ $m") || exit 1 ; done
      -
        name: terraform fmt check
        run: terraform fmt -list=true -write=false -check -recursive
